title: Trial && Error
description: Intrusive Thoughts & Lost Bits
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
sass:
  load_paths:
    - assets/css
